language: python
python:
- '3.6'
script:
- pytest
services:
- redis-server
deploy:
  password:
    secure: KZlre19SOU+CZJYmzZfe27zWYgspp0WzotJuDTWIw6K85VyaXcXYLFsBWikNGxRqKOl69ciPGQTTb8PmI8FoTJ1Xq+9taBrJgdz/aEtTNo1u8uV/HLiFTTNcPztUV1ZBKhgdgWW8vSPgtAdIVgJQ/EP/xEYX1mytBFvUUnNcA5Rx5Tk/j3jRbox0gOIg/iVWg4f0YKKx3VfKlyHyUAD0xeAGyGpuNcUfUwXXbWZNqU6n3+IcVi9AXBk1PNLzrS/2C44xUek1yQc97YiV1ecAkEV6L2g3BHsilFeslP6kVDlvIjhhxQIDXPJ8zksIKl+0ZoLB9lpwejy5/iY3FtxZnSMFqNLzF067KdvJ8gPNNw7H0NRBcVs7732/dYlhp0kGANOykrRqksQR0K4InEgj9zVqHCKrK9BPxlYZRkFNK99+iFAHTK6ep3ftTaAtiDohXhIdIor6koRob+J8KHvocDu76E62eFo5oYxrlFQ4UTFYn+DM9mLfULALWyJ4yqcRkrv+lpn5ayAKAjdGU2ar2ZrYFmuhKbAhKltHTZVj8CHJVX084uwf+KTwiJv8DQVFHaKz+JLYscgBmtUIjPhGSIm5v12ovI7nWDh1W2dWd0yQRhJByo7Vs0gwS9QLsZIlvKnguamLjbHBO2lCpwxFx9veE3Hi7TAAMidmaETlNn4=
  provider: pypi
  user: dmarkey
  on:
    tags: true
